[project]
name = "hvicorn"
version = "0.2.0"
description = "A simple hack.chat bot framework with type hinting"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic==2.7.3",
    "setuptools==70.0.0",
    "websocket-client==1.8.0",
    "websockets==12.0",
]
